kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-jenkins
  generation: 28
  labels:
    dce.daocloud.io/component: jenkins-jenkins
    dce.daocloud.io/app: jenkins
  namespace: cicd
  resourceVersion: '7634960'
  creationTimestamp: '2019-04-16T13:09:21+00:00'
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2019-04-16T13:09:21+00:00","generation":17,"labels":{"dce.daocloud.io/app":"jenkins","dce.daocloud.io/component":"jenkins-jenkins"},"name":"jenkins-jenkins","namespace":"cicd","resourceVersion":"3826391","selfLink":"/apis/apps/v1/namespaces/cicd/deployments/jenkins-jenkins","uid":"d9b9ff05-6048-11e9-8f6c-0242ac120002"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"dce.daocloud.io/component":"jenkins-jenkins"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cni.daocloud.io/ip-addrs":"[]"},"labels":{"dce.daocloud.io/app":"jenkins","dce.daocloud.io/component":"jenkins-jenkins"},"name":"jenkins-jenkins"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"jenkins","operator":"In","values":["jenkins"]}]}]}}},"containers":[{"image":"10.6.1.2/daocloud/jenkins:latest","imagePullPolicy":"Always","name":"jenkins-jenkins","resources":{"limits":{"cpu":"2","memory":"4294967296"},"requests":{"cpu":"0","memory":"0"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home","name":"hostpath-4d8211ec"},{"mountPath":"/home/jenkins","name":"hostpath-0cd2d57c"}]}],"dnsPolicy":"Default","imagePullSecrets":[{"name":"jenkins-jenkins-10.6.1.2"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"jenkins","serviceAccountName":"jenkins","terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/var/jenkins_home","type":""},"name":"hostpath-4d8211ec"},{"hostPath":{"path":"/home/jenkins","type":""},"name":"hostpath-0cd2d57c"}]}}}}
  selfLink: /apis/apps/v1/namespaces/cicd/deployments/jenkins-jenkins
  uid: d9b9ff05-6048-11e9-8f6c-0242ac120002
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      dnsPolicy: Default
      securityContext: {}
      serviceAccountName: jenkins
      schedulerName: default-scheduler
      serviceAccount: jenkins
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - operator: In
                    values:
                      - jenkins
                    key: jenkins
      volumes:
        - hostPath:
            path: /var/jenkins_home
            type: ''
          name: hostpath-4d8211ec
        - hostPath:
            path: /home/jenkins
            type: ''
          name: hostpath-0cd2d57c
      imagePullSecrets:
        - name: jenkins-jenkins-10.6.1.2
      containers:
        - terminationMessagePath: /dev/termination-log
          name: jenkins-jenkins
          image: '10.6.1.2/daocloud/jenkins:latest'
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: hostpath-4d8211ec
            - mountPath: /home/jenkins
              name: hostpath-0cd2d57c
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '2'
              memory: '4294967296'
    metadata:
      labels:
        dce.daocloud.io/component: jenkins-jenkins
        dce.daocloud.io/app: jenkins
      name: jenkins-jenkins
      annotations:
        cni.daocloud.io/ip-addrs: '[]'
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      dce.daocloud.io/component: jenkins-jenkins
status:
  replicas: 1
  observedGeneration: 28
  updatedReplicas: 1
  availableReplicas: 1
  readyReplicas: 1
  conditions:
    - status: 'True'
      lastUpdateTime: '2019-04-17T03:24:42+00:00'
      lastTransitionTime: '2019-04-16T13:09:21+00:00'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "jenkins-jenkins-6d69ccd59" has successfully progressed.
      type: Progressing
    - status: 'True'
      lastUpdateTime: '2019-05-20T06:52:42+00:00'
      lastTransitionTime: '2019-05-20T06:52:42+00:00'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
      type: Available

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-jenkins
  labels:
    dce.daocloud.io/app: jenkins
  namespace: cicd
  resourceVersion: '3826721'
  creationTimestamp: '2019-04-16T13:09:22+00:00'
  annotations:
    io.daocloud.dce.serviceSelectorType: service
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"io.daocloud.dce.serviceSelectorType":"service"},"creationTimestamp":"2019-04-16T13:09:22+00:00","labels":{"dce.daocloud.io/app":"jenkins"},"name":"jenkins-jenkins","namespace":"cicd","resourceVersion":"3757110","selfLink":"/api/v1/namespaces/cicd/services/jenkins-jenkins","uid":"d9e72442-6048-11e9-8f6c-0242ac120002"},"spec":{"clusterIP":"172.27.157.3","externalTrafficPolicy":"Cluster","ports":[{"name":"jenkins-jenkins-8080","nodePort":31600,"port":8080,"protocol":"TCP","targetPort":8080},{"name":"jenkins-jenkins-50000","nodePort":32663,"port":50000,"protocol":"TCP","targetPort":50000}],"selector":{"dce.daocloud.io/component":"jenkins-jenkins"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  selfLink: /api/v1/namespaces/cicd/services/jenkins-jenkins
  uid: d9e72442-6048-11e9-8f6c-0242ac120002
spec:
  selector:
    dce.daocloud.io/component: jenkins-jenkins
  externalTrafficPolicy: Cluster
  clusterIP: 172.27.157.3
  sessionAffinity: None
  type: NodePort
  ports:
    - targetPort: 8080
      protocol: TCP
      port: 8080
      name: jenkins-jenkins-8080
      nodePort: 31600
    - targetPort: 50000
      protocol: TCP
      port: 50000
      name: jenkins-jenkins-50000
      nodePort: 32663
status:
  loadBalancer: {}

